# Generated by Django 4.2.11 on 2024-04-03 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_domain_options_alter_tenant_options_and_more'),
        ('authentication', '0002_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.teams', verbose_name='Team'),
        ),
    ]
