# Generated by Django 4.2.11 on 2024-04-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
    ]
