# Generated by Django 4.2.11 on 2024-04-03 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_teams_tenant_tenant_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='members',
        ),
        migrations.AddField(
            model_name='teams',
            name='tenant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customers.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_team', to='customers.teams'),
        ),
    ]
