# Generated by Django 4.2.11 on 2024-03-31 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_tenant_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
