# Generated by Django 4.2.11 on 2024-04-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_teams_members_teams_tenant_alter_tenant_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='tenant',
        ),
    ]
