# Generated by Django 4.2.11 on 2024-04-03 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_teams_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='team',
        ),
        migrations.AddField(
            model_name='teams',
            name='tenant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
