# Generated by Django 4.2.11 on 2024-04-03 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0005_alter_domain_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(help_text='Add members to this team.', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
